In [1]:
import numpy as np


In [11]:
l=[1,2,3,4,5]
arr=np.array(l)
type(arr)
# N dimensional array

numpy.ndarray

In [10]:
l=[1,2,3,4,5,'Ajay']
np.array(l)
#automatically converted to string because of heterogenous data

array(['1', '2', '3', '4', '5', 'Ajay'], dtype='<U21')

In [12]:
l=[1,2,3,4,5,2.5]
np.array(l)
#automatically converted to float because of heterogenous data

array([1. , 2. , 3. , 4. , 5. , 2.5])

In [38]:
arr1=np.array([[1,2,3],[4,5,6]])
arr1

array([[1, 2, 3],
       [4, 5, 6]])

In [61]:
arr1.ndim #Two Dimensional

2

In [62]:
l=[1,2,3]
np.asarray(l)   #initial function to convert to an array and after this "np.array" came

array([1, 2, 3])

In [70]:
np.asanyarray([1,2,3])    # "asanyarray" will convert the input to an 'ndarray'
                        # but if something is already an array it will pass ndarray subclass through.

array([1, 2, 3])

In [72]:
#tuple into array
t=([1,2,3],[4,5,6])
type(t)

tuple

In [73]:
np.array(t)

array([[1, 2, 3],
       [4, 5, 6]])

In [75]:
arr

[1, 2, 3, 4, 5]

In [77]:
#Accessing elements of array
arr[3]

4

In [78]:
#Array is mutable
arr[0]=1000
arr

[1000, 2, 3, 4, 5]

In [95]:
#shallow copy
arr[0]=5000
arr[2]=1000
arr

[5000, 2, 1000, 4, 5]

In [97]:
#deep copy >> change in one array will not reflect in other

b=arr.copy()
b[2]=11000
b

[5000, 2, 11000, 4, 5]

In [ ]:
#To create an array>> multiple approaches >>np.array , np,asarray, np.asanyarray

In [99]:
#construct an array by executing a function over each coordinate
np.fromfunction(lambda i, j:i==j,(3,3))

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [100]:
#dimension of an array
arr1.ndim

2

In [102]:
#Shape of an array
arr1.shape

(2, 3)

In [103]:
#Size of an array
arr1.size

6

In [106]:
np.fromfunction(lambda i,j:i*j,(3,3))

array([[0., 0., 0.],
       [0., 1., 2.],
       [0., 2., 4.]])

In [113]:
for i in range(5):
    print(i)

0
1
2
3
4


In [110]:
[i for i in range(5)]

[0, 1, 2, 3, 4]

In [114]:
(i for i in range(5))
#generator object

<generator object <genexpr> at 0x1092cfd00>

In [115]:
iterator= (i for i in range(5))
iterator
#generator object

<generator object <genexpr> at 0x1099a44c0>

In [116]:
np.fromiter(iterator, int)
#fromiter

array([0, 1, 2, 3, 4])

In [119]:
np.fromstring('22 23 24',sep=" ")
#fromstring >> by default it is float and values inside string should be numerical

array([22., 23., 24.])

In [118]:
np.fromstring('22 23 24',sep=" ", dtype=int)
#fromstring >> converted from float to int

array([22, 23, 24])

In [125]:
#Split
string='Ajay,Vijay,Rajeev'
string.split(",")

['Ajay', 'Vijay', 'Rajeev']

In [126]:
np.array(string.split(","))

array(['Ajay', 'Vijay', 'Rajeev'], dtype='<U6')

In [127]:
list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [129]:
#arange
np.arange(1,10,0.1)

array([1. , 1.1, 1.2, 1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2. , 2.1, 2.2,
       2.3, 2.4, 2.5, 2.6, 2.7, 2.8, 2.9, 3. , 3.1, 3.2, 3.3, 3.4, 3.5,
       3.6, 3.7, 3.8, 3.9, 4. , 4.1, 4.2, 4.3, 4.4, 4.5, 4.6, 4.7, 4.8,
       4.9, 5. , 5.1, 5.2, 5.3, 5.4, 5.5, 5.6, 5.7, 5.8, 5.9, 6. , 6.1,
       6.2, 6.3, 6.4, 6.5, 6.6, 6.7, 6.8, 6.9, 7. , 7.1, 7.2, 7.3, 7.4,
       7.5, 7.6, 7.7, 7.8, 7.9, 8. , 8.1, 8.2, 8.3, 8.4, 8.5, 8.6, 8.7,
       8.8, 8.9, 9. , 9.1, 9.2, 9.3, 9.4, 9.5, 9.6, 9.7, 9.8, 9.9])

In [130]:
#linspace>> gives 10 number between 1 and 5
np.linspace(1,5,10)

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])